### ISSUE TITLE
Unable to create new Gatsby site with gatsby-starter-nehalem

### ISSUE THREAD

**Issue by peterdalydickson** [nehalist/gatsby-starter-nehalem#6]
I really want to use your excellent theme https://github.com/nehalist/gatsby-theme-nehalem, but I've not had any joy with adding it to an existing site.

And when I attempt to use this starter, I get the attached error.

I'm new to this whole world, and don't have any idea how to even start troubleshooting!
[log.txt](https://github.com/nehalist/gatsby-starter-nehalem/files/4634023/log.txt)

**Comment by nehalist** [comment]
Most likely not an error with the theme and node-gyp instead, see https://github.com/nodejs/node-gyp/issues/809
