### ISSUE TITLE
Theme MDX support?

### ISSUE THREAD

**Issue by kulykaldr** [nehalist/gatsby-starter-nehalem#7]
Hello! Your starter and theme is great, I like it
But I think it needed a MDX support instead of usually only markdown support
Will you insert in your theme the MDX support in near future?
Thanks!

**Comment by nehalist** [comment]
Unfortunately I don't think that I'll find the time to update the theme in the near future.

**Comment by kulykaldr** [comment]
> Unfortunately I don't think that I'll find the time to update the theme in the near future.

Yes, I understand. Thanks for answer
